### ISSUE TITLE
cannot build on Alpine 

### ISSUE THREAD

**Issue by schmod** [imagemin/optipng-bin#110]
I'm unable to install this package with any of the current Alpine Linux-derived Node.JS Docker images:

```
$ docker run --rm -it node:12-alpine /bin/sh
/ # yarn add optipng-bin
yarn add v1.19.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /node_modules/optipng-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /node_modules/optipng-bin
Output:
⚠ spawn /node_modules/optipng-bin/vendor/optipng ENOENT
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c ./configure --with-system-zlib --prefix="/node_modules/optipng-bin/vendor" --bindir="/node_modules/optipng-bin/vendor"

Checking for gcc...
Using pre-configured libpng...
Checking for system zlib...
./configure: error: missing zlib or incorrect zlib version
./configure: note: zlib version 1.2.1 or higher is required

    at /node_modules/execa/index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

Installing `zlib` and `zlib-dev` does not appear to rectify the situation.  All recent releases of alpine [should be using zlib v1.2.11](https://pkgs.alpinelinux.org/packages?name=zlib&branch=v3.10).

**Comment by popkirby** [comment]
I found installing following packages solves this issue:
```sh
apk --no-cache add g++ make libpng-dev
```

**Comment by phiresky** [comment]
You can also just do `apk add libc6-compat` then the precompiled binary from https://raw.githubusercontent.com/imagemin/optipng-bin/v7.0.0/vendor/linux/x64/optipng will work and it won't have to compile it. It doesn't by default since:

```
ldd .../vendor/optipng

/lib64/ld-linux-x86-64.so.2
...
```

that file does not exist, but it is provided by libc6-compat: https://pkgs.alpinelinux.org/contents?file=ld-linux-x86-64.so.2&path=&name=&branch=&repo=&arch=

**Comment by ogonkov** [comment]
Without `libc6-compat` on Alpine this package is trying to recompile itself, thanks for that tip!

**Comment by 1000ch** [comment]
Please make sure to install dependencies to install this package like https://github.com/imagemin/optipng-bin/issues/110#issuecomment-574049204.
