### ISSUE TITLE
Mac OS 10.9 optipng cannot execute binary file

### ISSUE THREAD

**Issue by strann** [imagemin/optipng-bin#37]
After upgrading `grunt-contrib-imagemin` to 0.7.0 today I can't run my imagemin tasks on OSX, Ubuntu works just fine.

I noticed in the `package.json` for `imagemin-optipng` it references:

```
"optipng-bin": "^0.3.3",
```

As a dependency when the project seems to be named `node-optipng-bin` now, related?

Heres the error (true root path swapped with `/path/to`)

```
Warning: Command failed: /path/to/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng: /path/to/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng: cannot execute binary file
```

**Comment by samvdb** [comment]
remove /usr/local/bin/optipng and install optipng-bin again through npm.
