### ISSUE TITLE
Windows 7 install fails

### ISSUE THREAD

**Issue by kitsguru** [imagemin/optipng-bin#54]
Window 7 64 bit

As part of  "grunt-contrib-imagemin": "^0.9.2", Everything installs OK except
I get the following error on optipng-bin:
````
> optipng-bin@2.0.4 postinstall J:\integra\html\node_modules\grunt-contrib-image
min\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin

> node lib/install.js

  ‼ EPERM, symlink 'c:\ProgramData\chocolatey\bin\optipng.exe'
  ‼ optipng pre-build test failed
  i compiling from source
  × Error: ./configure --with-system-zlib --prefix="J:\integra\html\node_modules
\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node
_modules\optipng-bin\vendor" --bindir="J:\integra\html\node_modules\grunt-contri
b-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\opti
png-bin\vendor" && make install
Command failed: '.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

````

**Comment by kevva** [comment]
Try running as an administrator.

**Comment by kitsguru** [comment]
Removing the existing optipng didn't fix the issue, but running git bash as administrator did the trick. It took a bit to find out how to set up git bash to run as administrator but worth it. It was a simple modification.

Thanks for the tip.

**Comment by kevva** [comment]
Great to hear!

**Comment by qunybble** [comment]
I also found that optipng installation and configuration will show a similar issue if there is a space in the path to the directory where you are running npm install. In my case this also required renaming my Jenkins project using npm/gulp for continuous deployments to not have spaces.
