### ISSUE TITLE
Check optipng installed in system first

### ISSUE THREAD

**Issue by KostyaSha** [imagemin/optipng-bin#55]
Is there any possibility to use optipng installed in environment and only then fallback to vendor and compilation?

**Comment by kevva** [comment]
We removed that functionality https://github.com/imagemin/optipng-bin/commit/e4d8beb197a755b7d2964fdcfec6e05c1767959a#diff-6d186b954a58d5bb740f73d84fe39073L18.

**Comment by KostyaSha** [comment]
Why?

**Comment by KostyaSha** [comment]
your vendor compiled binaries doesn't work on centos6, SF fails in 40% of installations because they have issues last months and module can't fetch source archive. Using vendor bins instead of system available (right compiled and trusted) is dangerous so this should be optional.

**Comment by jdpedrie** [comment]
:-1:
