### ISSUE TITLE
Hanging when node_modules is a symlink (since version 2.0.1)

### ISSUE THREAD

**Issue by andreitognolo** [imagemin/optipng-bin#56]
I'm a Snap CI developer and there's a customer of us who is facing a problem that seems to be a bug when the node_module is a symlink. 

I've created a [project](https://snap-ci.com/andreitognolo/optipng-bin-hanging/branch/master) on Snap CI in order to illustrate the problem. @kevva, I've added you as a collaborator, so you can see the pipeline configuration [here](https://snap-ci.com/andreitognolo/optipng-bin-hanging/branch/master/configuration). Feel free to change it if you need.

Thank you.

-- Andrei Tognolo

**Comment by kevva** [comment]
https://github.com/imagemin/imagemin/issues/68
