### ISSUE TITLE
fails inside a docker container

### ISSUE THREAD

**Issue by dciccale** [imagemin/optipng-bin#57]
fails inside a docker container created from `node:latest`

```bash
root@d06adbb5fa5c:/home/app# gulp imagemin
[07:45:43] Using gulpfile /home/app/gulpfile.js
[07:45:43] Starting 'imagemin'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Command failed: /home/app/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng -strip all -clobber -force -fix -o 2 -out /tmp/d3fd1a87-7e45-4d50-bf61-30c1c6911a31 /tmp/4a577168-c7f5-4eac-8fc8-44944cee6894
/home/app/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng: 6: /home/app/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng: Syntax error: newline unexpected

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

**Comment by kevva** [comment]
https://github.com/imagemin/optipng-bin/issues/41

**Comment by dciccale** [comment]
i updated npm inside the container and re-installed imagemin dep and it worked thx

**Comment by dciccale** [comment]
it only works if i manually install imagemin inside the container i will have to include that in the dockerfile do you think of another better solution?

**Comment by kevva** [comment]
Never worked with imagemin using docker so unfortunately, no.

**Comment by treejanitor** [comment]
@dciccale Hmm, I hit the same issue with docker...  I tried to manually install _imagemin_ in the container but didn't have any luck with getting past the newline unexpected issue.  What did you do exactly?  I tried `npm install -g imagemin`

**Comment by dciccale** [comment]
@treejanitor i am using gulp-imagemin which uses this module, what I did in my Dockerfile is `RUN npm update -g npm && npm install gulp-imagemin` and it worked.

**Comment by treejanitor** [comment]
@dciccale Thanks - I'm using grunt, but hopefully it'll be the same...  I'll give it a shot.

**Comment by treejanitor** [comment]
@dciccale I couldn't get this to work for the life of me...  the issue is inside `optipng-bin` for some reason.  I just am going to skip crunching pngs for now.  I installed via `RUN npm update -g npm && npm install grunt-contrib-min` and also tried `RUN npm update -g npm && npm install optipng-bin` in the same way you did, but had no luck.  Thanks for the tip though.

**Comment by lenybernard** [comment]
@treejanitor did you figured out why it was failing ? I also experiencing this issue with a grunt app

**Comment by manchuck** [comment]
I was able to workaround this issue by switching to the node:6-wheezy container.  seems that by default, node:6 was built using the jessie ubuntu.  This package appears to have issues running on that flavor

**Comment by kevinkarwaski** [comment]
@manchuck you saved my day! Thanks for the wheezy tip, worked like a charm.

**Comment by manchuck** [comment]
@kevinkarwaski Seems that jessie ubuntu is using an ARM processor.  Something compiled along the way is causing issues.  Still have not gone through to figure out why that could be happening.

**Comment by dpayne9000** [comment]
thanks breh

**Comment by CITguy** [comment]
I just ran into this issue. I discovered that my docker setup was copying compiled npm binaries from my host to the guest container. However, you cannot guarantee that a container's cpu architecture will match that of your host. So, to avoid this issue, I would recommend adding `node_modules/` to a `.dockerignore` file so that the host-compiled binaries are not transferred to the guest.
