### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by luisrivera-co** [imagemin/optipng-bin#66]
Hello,

I support users behind a corporate firewall with SSL inspection. Nothing gets declared on the clients in terms of the proxy except that they need a copy of some certificates for any SSL connections to be recognized as valid.

I have set these certificates in the cafile variable in npm config. I still get this error when a user tries to install your package (as a dependency from imagemin).

> optipng-bin@3.1.0 postinstall /Users/lrivera/testnpm/node_modules/optipng-bin
> node lib/install.js

  ⚠ unable to verify the first certificate
  ⚠ optipng pre-build test failed
  ℹ compiling from source

I can get past it by turning off strict ssl or setting node to not fail on TLS failure, but that's not a great option.

I did read something in all my searching saying that maybe individual packages weren't reading from the cafile config variable. They specifically called out another package that set up a download (similar to what the install.js here does for what I can tell).

I'm not sure where I would see for sure that this package was checking for a cafile, but maybe you can help with this issue in general?

edit: I edited everything to try and make my request clearer.

**Comment by luisrivera-co** [comment]
Currently fixing issues like this by adding a function to user's bash profile.

npm-proxy-install() {
	NODE_TLS_REJECT_UNAUTHORIZED=0 npm install $1
}

This allows the user to use this command.

npm-proxy-install optipng

This way, SSL it's turned off for every npm install.

**Comment by sindresorhus** [comment]
We use [`request`](https://github.com/request/request) for the network requests, so I would recommend asking there. Not much we can do here.

**Comment by shinnn** [comment]
@sindresorhus No, imagemin uses [`got`](https://github.com/kevva/download/blob/390ca84000458c67e66028aa92cd9edbfd72f5d6/package.json#L33).
