### ISSUE TITLE
optping-bin does not compile

### ISSUE THREAD

**Issue by chfw** [imagemin/optipng-bin#69]
Hi all,

optipng-bin failed to compiled under centos 7.2

    > optipng-bin@3.1.1 postinstall /var/lib/jenkins/workspace/checkout/node_modules/optipng-bin
    > node lib/install.js
    
      ⚠ unable to get local issuer certificate
      ⚠ optipng pre-build test failed
      ℹ compiling from source
      ✖ Error: ./configure --with-system-zlib --prefix="/var/lib/jenkins/workspace/checkout/node_modules/optipng-bin/vendor" --bindir="/var/lib/jenkins/workspace/checkout/node_modules/optipng-bin/vendor" && make install
    Command failed: /bin/sh -c ./configure --with-system-zlib --prefix="/var/lib/jenkins/workspace/checkout/node_modules/optipng-bin/vendor" --bindir="/var/lib/jenkins/workspace/checkout/node_modules/optipng-bin/vendor"
    /bin/sh: ./configure: No such file or directory

What could have been done to find out why?

**Comment by shinnn** [comment]
> unable to get local issuer certificate

The error message perfectly explains why. Fix your network settings.
