### ISSUE TITLE
If optipng is found on the system it should use it

### ISSUE THREAD

**Issue by imduffy15** [imagemin/optipng-bin#72]
On a RHEL6 system I have preformed a yum install optipng it installed optipng to /usr/bin/optipng and i could launch it from my shell without issue.

When executing the module it attempted to download and compile optipng.

**Comment by shinnn** [comment]
I can say with confidence that this feature will soon bloats up the project issue tracker. Users often have broken global binaries. https://github.com/imagemin/imagemin/issues/89#issuecomment-81352440

**Comment by mrchief** [comment]
Same thing happens in docker containers. Compilation fails on Linux alpine and if it could use the binary on the system, this wouldn't be an issue.

**Comment by dhensen** [comment]
We run into the same problem described by @mrchief

**Comment by shinnn** [comment]
It's not a optipng-bin issue anyway. Discuss it on https://github.com/kevva/bin-wrapper/issues/50.
