### ISSUE TITLE
No output with spawn instead of execFile

### ISSUE THREAD

**Issue by mosquito1994** [imagemin/optipng-bin#76]
Excuse me, I'm using `child_process.spawn` instead of `child_process.execFile`, so my code change to

```
var spawn = require('child_process').spawn;
var optipng = require('optipng-bin');

var child = spawn(optipng, ['-out', 'output.png', 'input.png'], err => {
    console.log('Image minified!');
});

child.stdout.on('data',  (data) => {
  // do something
}); 
```
However I get no file compressed name "output.png". It seems compression doesn't start at all. Could you please help me?

**Comment by shinnn** [comment]
> Could you please help me? 

No. This is not a optipng-bin issue but just a question for Node.js usage. Use https://stackoverflow.com/ instead.
