### ISSUE TITLE
3.1.3 should not be a minor version update since it requires upgrading Node

### ISSUE THREAD

**Issue by vedraan** [imagemin/optipng-bin#87]
After `npm install` pulls that latest version of this package (moved from 3.1.2 to 3.1.3) you're no longer able to use it if you're not running Node 4+. This is an OK update to the code, but it is in my opinion not a patch change like it got marked on the latest release. It should instead increment the major version number to 4.0.0 (since it changes the requirements to use a package).

Here's the dependency chain a production build I am using relies on:
`grunt-contrib-imagemin@1.0.1 > imagemin@4.0.0 > imagemin-optipng@4.3.0 > optipng-bin@3.1.3`

The build is broken since the production server node version needs to be bumped, which is not a small task.

**Comment by 1000ch** [comment]
Ahhh, sorry, this is completely my mistake. I published for #84 patch with forgetting ES2015ify. I will publish patch again after reverting ES2015ify.

**Comment by 1000ch** [comment]
@vedraan Published `v3.1.4` including revert commit for ES2015ify.

**Comment by vedraan** [comment]
👍
